fix: change webhook for the upstream nginx version
hivemq/helm-charts pull request #47
Opened 2022-03-04 13:28 UTC by hurtadosanti

https://github.com/jet/kube-webhook-certgen/issues/30

2022-03-04 13:39 UTC, sbaier1 approved these changes
LGTM, i assume it's a drop-in replacement then?

2022-03-04 13:45 UTC, sbaier1 requested changes
oversaw the missing Chart.yaml version update, please add it

2022-03-04 13:45 UTC, sbaier1 commented on charts/hivemq-operator/CHANGELOG.md
> +# chart 0.9.4
btw, you need to update the Chart.yaml to reflect the version update

2022-03-07 09:52 UTC, hurtadosanti commented
> Yes I test it with Kubernetes using k3s versions {"v1.18.20-k3s1", "v1.19.16-k3s1", "v1.20.15-k3s1", "v1.21.10-k3s1", "v1.22.7-k3s1", "v1.23.4-k3s1"}

2022-03-07 09:54 UTC, sbaier1 approved these changes
LGTM 👍

2022-03-07 09:55 UTC, merged